DECLARE @USERNAME NVARCHAR(100)
SET @USERNAME = 'REGIONS\8600-90-331' -- !” ¿«¿“‹ ”◊≈“Õ”ﬁ «¿œ»—‹
DECLARE @SCRIPT NVARCHAR(4000)

EXEC dbo.sp_grantlogin @loginame = @USERNAME
EXEC dbo.sp_grantdbaccess @loginame = @USERNAME, @name_in_db = @USERNAME

SET @SCRIPT = 'GRANT SELECT ON EMPLOYERS_SID_TBL TO [' + @USERNAME + ']'
EXEC sp_executesql @SCRIPT

SET @SCRIPT = 'GRANT SELECT ON ORDERS TO [' + @USERNAME + ']'
EXEC sp_executesql @SCRIPT

SET @SCRIPT = 'GRANT SELECT ON DIS_FACE TO [' + @USERNAME + ']'
EXEC sp_executesql @SCRIPT

SET @SCRIPT = 'GRANT SELECT ON SUBDIVISION2 TO [' + @USERNAME + ']'
EXEC sp_executesql @SCRIPT

SET @SCRIPT = 'GRANT SELECT ON DEPARTMENTS TO [' + @USERNAME + ']'
EXEC sp_executesql @SCRIPT

SET @SCRIPT = 'GRANT SELECT ON EMPLOYERS_SID_TBL TO [' + @USERNAME + ']'
EXEC sp_executesql @SCRIPT

SET @SCRIPT = 'GRANT SELECT ON EMPLOYERS TO [' + @USERNAME + ']'
EXEC sp_executesql @SCRIPT

SET @SCRIPT = 'GRANT SELECT ON FACES_MAIN_TBL TO [' + @USERNAME + ']'
EXEC sp_executesql @SCRIPT

SET @SCRIPT = 'GRANT SELECT ON USER_INFO TO [' + @USERNAME + ']'
EXEC sp_executesql @SCRIPT

SET @SCRIPT = 'GRANT SELECT ON MOVES TO [' + @USERNAME + ']'
EXEC sp_executesql @SCRIPT

SET @SCRIPT = 'GRANT EXECUTE ON DICTIONARY_VACATION_FACES_FN_DAYS TO [' + @USERNAME + ']'
EXEC sp_executesql @SCRIPT

SET @SCRIPT = 'GRANT SELECT ON VACATION_REAL TO [' + @USERNAME + ']'
EXEC sp_executesql @SCRIPT
