/* Увольнение сотрудников */

DECLARE @dDate1 DATETIME, @dDate2 DATETIME, @dNow DATETIME, @Days INT 

SET @Days = 4 -- количество дней +- от текущей даты

SET @dDate1 = DATEADD(DAY, -@Days, GETDATE())
SET @dDate2 = DATEADD(DAY, @Days, GETDATE())
SET @dNow = GETDATE()

SELECT DISTINCT 		
	 EMPLOYERS.LINK
	,D.FULL_NAME
	,FACES_MAIN_TBL.FIO_SHORT [FIO]
	,EMPL.[LOGIN]	
	,STF.CODE [SUBDIV_CODE]	
	,DIS.[SUBDIV] [SUBDIV_NAME]
	,DIS.[POST] [POST_NAME]
	,DIS.[TAB_NUM]
	,DIS.[DIS_DATE]
	,REASON.[SNAME] [DESCRIPTION]	
	,ORD.NUMBER ORD_NUMBER
	,ORD.[DATE] ORD_DATE
FROM ORDERS_TBL ORD
	LEFT JOIN ITEM_DIS_FACE DIS ON ORD.LINK = DIS.ORDER_LINK
	INNER JOIN DICTIONARY_PUV AS REASON ON DIS.REASON = REASON.LINK	
	LEFT JOIN SUBDIV STF ON STF.NAME = DIS.SUBDIV AND STF.DATE_END > GETDATE()
	LEFT JOIN SUBDIV_HEAD STF_HEAD ON STF_HEAD.LINK = STF.LINK_UP
	INNER JOIN DEPARTMENTS_TBL AS D ON ORD.LINK_DEP_OWN = D.LINK	
	LEFT JOIN EMPLOYERS_SID_TBL EMPL ON EMPL.LINK_EMPL = DIS.LINK_EMPL
	LEFT JOIN EMPLOYERS_TBL EMPLOYERS ON EMPLOYERS.LINK = EMPL.LINK_EMPL
	LEFT JOIN FACES_MAIN_TBL ON FACES_MAIN_TBL.LINK = EMPLOYERS.FACE_LINK
WHERE ORD.[TYPE] IN (3, 103)	
	AND (DIS.ACTIVE = 1)	
	AND ORD.LINK_DEP_OWN IN (SELECT DISTINCT LINK FROM DICTIONARY_DEPARTMENT_ALL WHERE CODE = '8600')
	AND DIS_DATE BETWEEN @dDate1 AND @dDate2
	AND EMPLOYERS.LINK IS NOT NULL
	AND STF_HEAD.DEP_LINK = ORD.LINK_DEP_OWN
ORDER BY DIS.[DIS_DATE]
