/* Увольнение сотрудников */

DECLARE @dDate1 DATETIME, @dDate2 DATETIME, @dNow DATETIME, @nOrderItemStatus INT, @Days INT 

SET @Days = 4 -- количество дней +- от текущей даты
SET @nOrderItemStatus = 1 -- статус пунктов приказа

SET @dDate1 = DATEADD(DAY, -@Days, GETDATE())
SET @dDate2 = DATEADD(DAY, @Days, GETDATE())
SET @dNow = GETDATE()

SELECT 	 
	 EMPLOYERS.LINK
	,DEP.FULL_NAME
	,FACES_MAIN_TBL.FIO_SHORT [FIO]
	,EMPL.[LOGIN]	
	,STF.CODE [SUBDIV_CODE]
	,DIS.[SUBDIV] [SUBDIV_NAME]
	,DIS.[POST] [POST_NAME]
	,DIS.[TAB_NUM]
	,DIS.[DIS_DATE]
	,DIS.[REASON_NAME] [DESCRIPTION]	
FROM ORDERS ORD
	LEFT JOIN DIS_FACE DIS ON ORD.LINK = DIS.ORDER_LINK
	LEFT JOIN SUBDIVISION2(@dNow) STF ON STF.NAME = DIS.SUBDIV
	LEFT JOIN DEPARTMENTS DEP ON DEP.LINK = ORD.DEP_LINK
	LEFT JOIN EMPLOYERS_SID_TBL EMPL ON EMPL.LINK_EMPL = DIS.LINK_EMPL
	LEFT JOIN EMPLOYERS ON EMPLOYERS.LINK = EMPL.LINK_EMPL
	LEFT JOIN FACES_MAIN_TBL ON FACES_MAIN_TBL.LINK = EMPLOYERS.FACE_LINK
WHERE ORD.[TYPE] IN (3, 103)	
	AND (DIS.ACTIVE = @nOrderItemStatus)
	AND ORD.DEP_LINK IN (SELECT DEP_LINK FROM USER_INFO)
	AND DIS_DATE BETWEEN @dDate1 AND @dDate2
