DECLARE @dDate1 DATETIME, @dDate2 DATETIME,	@nOtborLink1 INT

DECLARE @Days INT 
SET @Days = 4


SET @dDate1 = DATEADD(DAY, @Days * -1, GETDATE())
SET @dDate2 = DATEADD(DAY, @Days, GETDATE())

SET @nOtborLink1 = 0

DECLARE @nOrderItemStatus INT /*Статус пунктов приказа*/	
SET @nOrderItemStatus =1

SELECT 
	ITV.TYPE_NAME, 
	dbo.DICTIONARY_VACATION_FACES_FN_DAYS(ITV.LINK) COUNT_DAYS, 
	ITV.PERIOD_BEGIN, 
	ITV.PERIOD_END, 
	ITV.DATE_BEGIN, 
	ITV.DATE_END_REAL, 
	ITV.FIO, 
	ITV.TAB_NUM, 
	ITV.SUBDIV, 
	ITV.POST, 
	--DEP.LINK, 
	ORD4.LINK, 
	ITV.LINK ITV_LINK
FROM DEPARTMENTS DEP, ORDERS ORD4, dbo.VACATION_REAL ITV
WHERE ( ORD4.LINK = ITV.ORDER_LINK  AND (@nOrderItemStatus < 0 OR ITV.ACTIVE = @nOrderItemStatus) )
	AND DEP.LINK=(SELECT DEP_LINK FROM USER_INFO)
	AND ITV.DATE_BEGIN BETWEEN @dDate1 AND @dDate2
	AND ORD4.DEP_LINK = DEP.LINK
	AND ORD4.TYPE IN (4, 104, 15)
	AND (@nOtborLink1=0 OR EXISTS(SELECT RECORD FROM OBJECT_VAR_DICTIONARY_VACATION_TABLE WHERE LINK_UP=@nOtborLink1 AND RECORD = ITV.TYPE_LINK))
	AND ITV.TYPE_CODE IN (22, 48, 49)