/* Отпуска */

DECLARE @dDate1 DATETIME, @dDate2 DATETIME, @nOrderItemStatus INT, @Days INT 

SET @Days = 4 -- количество дней +- от текущей даты
SET @nOrderItemStatus = 1 -- статус пунктов приказа

SET @dDate1 = DATEADD(DAY, -@Days, GETDATE())
SET @dDate2 = DATEADD(DAY, @Days, GETDATE())

SELECT 
	ITV.TYPE_NAME, 
	DEP.FULL_NAME [DEP_NAME],
	dbo.DICTIONARY_VACATION_FACES_FN_DAYS(ITV.LINK) COUNT_DAYS, 
	ORD4.NUMBER ORD_NUMBER,
	ORD4.[DATE] ORD_DATE,
	ITV.DATE_BEGIN, 
	ITV.DATE_END_REAL,	
	EMPL.[LOGIN],
    FACES_MAIN_TBL.FIO_SHORT [FIO],
	ITV.TAB_NUM, 
	ITV.SUBDIV, 
	ITV.POST,	
	ORD4.LINK, 
	ITV.LINK ITV_LINK
FROM DEPARTMENTS DEP, ORDERS ORD4, dbo.VACATION_REAL ITV
	LEFT JOIN EMPLOYERS ON EMPLOYERS.LINK = ITV.LINK_EMPL
	LEFT JOIN FACES_MAIN_TBL ON FACES_MAIN_TBL.LINK = EMPLOYERS.FACE_LINK
	LEFT JOIN EMPLOYERS_SID_TBL EMPL ON EMPL.LINK_EMPL = ITV.LINK_EMPL
WHERE (ORD4.LINK = ITV.ORDER_LINK  AND (ITV.ACTIVE = @nOrderItemStatus))
	AND DEP.LINK=(SELECT DEP_LINK FROM USER_INFO)
	AND ITV.DATE_BEGIN BETWEEN @dDate1 AND @dDate2
	AND ORD4.DEP_LINK = DEP.LINK
	AND ORD4.TYPE IN (4, 104, 15)	
	AND ITV.TYPE_CODE IN ('03', '22', '48', '49') -- указать коды отпусков
	/*
	посмотреть коды отпусков можно в ПК "ДКС", задача "Кадры", ветка "Справочники - Учет рабочего времени - Виды отпусков"
	*/